### PR TITLE
Link added

### PR DESCRIPTION
**Pull request by rajdama**

### CODE REVIEW

**Review by Arun-kc — CHANGES_REQUESTED** [review]
You can add the link to addFields so that user can view this link in the embed while using the command `zoro info`
image
Just replace the 
`name: 'Website',
value: 'coming soon...' `
with 
`name: 'Website',
value: 'https://zorobot.vercel.app/' `

Thanks for your help @rajdama 👍

**Comment by rajdama** [comment]
Done

**Review by Arun-kc — APPROVED** [review]
Looks good. 👍
Feel free to open new issues  and PR's for the same 🙌

**Comment by Arun-kc** [comment]
Closes issue #6 
Good work @rajdama

**Comment by rajdama** [comment]
> Looks good. 👍
> Feel free to open new issues and PR's for the same 🙌

Yea sure

**Pull request merged**
